# Refer to below link to check the scylla operator customization values.
# https://github.com/scylladb/scylla-operator/blob/master/helm/scylla-operator/values.yaml
image:

# Scylla-Operator Release Version Tag
  tag: 1.7.4

# Change log level
logLevel: 2

# Resources allocated to Scylla Operator pods
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Node selector for Scylla Operator pods
nodeSelector:
  cloud.google.com/gke-nodepool: "scylla-generic"

# Tolerations for Scylla Operator pods
tolerations:
- key: role
  operator: Equal
  value: scylla-generic
  effect: NoSchedule

# Node selector for Webhook Server pods
webhookServerNodeSelector:
  cloud.google.com/gke-nodepool: "scylla-generic"

# Tolerations for Webhook Server pods
webhookServerTolerations:
- key: role
  operator: Equal
  value: scylla-generic
  effect: NoSchedule
